### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yanglin-code** [wenke727/ST-MapMatching#10]
按照readMe里的环境安装完了，运行demo报了下面这个错是为啥呀

D:\Anaconda3\envs\stmm\python.exe D:\pythonProject\useful\ST-MapMatching\demo.py 
2023-04-12 16:31:06.090 | INFO     | mapmatching.matching:matching:75 - 

start
2023-04-12 16:31:06.095 | INFO     | mapmatching.utils.timer:inner:40 - align_crs, cost:  4.00 ms
2023-04-12 16:31:06.099 | DEBUG    | mapmatching.geo.ops.simplify:simplify_trajetory_points:115 - Trajectory compression rate: 100.0% (6 -> 6)
2023-04-12 16:31:06.099 | INFO     | mapmatching.utils.timer:inner:40 - simplify, cost:  4.00 ms
2023-04-12 16:31:06.102 | INFO     | mapmatching.utils.timer:inner:40 - _get_cands, cost:  2.00 ms
2023-04-12 16:31:06.509 | INFO     | mapmatching.utils.timer:inner:40 - _project, cost:  407.39 ms
2023-04-12 16:31:06.517 | INFO     | mapmatching.utils.timer:inner:40 - _filter_candidate, cost:  3.00 ms
2023-04-12 16:31:06.517 | INFO     | mapmatching.utils.timer:inner:40 - get_k_neigh_geoms, cost:  418.40 ms
2023-04-12 16:31:06.532 | INFO     | mapmatching.utils.timer:inner:40 - construct_graph, cost:  14.01 ms
2023-04-12 16:31:06.537 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905469, -221936732), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.538 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905469, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.538 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905469, 884162176), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.538 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905469, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.538 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905469, -1786905389), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.538 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-221936732, -63073670), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.538 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073670, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.538 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073670, 884162176), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.538 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073670, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.538 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073670, -1786905389), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.538 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905409, -221936732), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.539 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905409, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.539 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905409, 884162176), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.539 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905409, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.539 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905409, -1786905389), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.539 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905398, -221936732), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.539 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905398, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.539 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905398, 884162176), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.539 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905398, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.539 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905398, -1786905389), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.543 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905427, -221936732), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.543 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905427, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.543 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905427, 884162176), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.543 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905427, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.543 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-1786905427, -1786905389), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.563 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-221936732, -63073670), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.563 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073670, 884162176), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.563 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073670, -1786905389), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.563 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073670, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.563 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073670, 845273725), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.580 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073670, 1050142912), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.580 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073670, -63073664), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.581 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073670, -63073649), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.594 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (1050142912, 1050143526), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.594 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (1050142912, -63073594), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.594 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (1050142912, -63073594), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.594 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (1050142912, -63073579), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.594 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (1050142912, -63073578), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.594 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073676, 1050143526), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.594 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073676, -63073594), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.594 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073676, -63073594), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.594 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073676, -63073579), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.594 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073676, -63073578), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.608 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073578, -63073580), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.608 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073578, 845273726), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.608 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073578, 845273726), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.608 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073578, -63073580), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.608 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073578, 1050143546), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.609 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (1050143526, -63073580), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.609 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (1050143526, 845273726), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.609 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (1050143526, 845273726), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.609 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (1050143526, -63073580), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.609 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (1050143526, 1050143546), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.609 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073597, -63073580), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.609 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073597, 845273726), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.609 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073597, 845273726), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.609 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073597, -63073580), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.609 | DEBUG    | mapmatching.graph.astar:has_edge:48 - Trip (-63073597, 1050143546), `src` not in graph, `dst` not in graph
2023-04-12 16:31:06.629 | INFO     | mapmatching.utils.timer:inner:40 - spatial_analysis, cost:  110.61 ms
2023-04-12 16:31:06.639 | INFO     | mapmatching.utils.timer:inner:40 - get_path, cost:  10.01 ms
2023-04-12 16:31:06.645 | INFO     | mapmatching.utils.timer:inner:40 - align_crs, cost:  2.00 ms
2023-04-12 16:31:06.966 | INFO     | mapmatching.utils.timer:inner:40 - matching, cost:  876.84 ms
Traceback (most recent call last):
  File "D:\pythonProject\useful\ST-MapMatching\demo.py", line 27, in <module>
    proj_traj = matcher.project(traj, path)
  File "D:\pythonProject\useful\ST-MapMatching\mapmatching\matching.py", line 211, in project
    ps = project_points_2_linestrings(
  File "D:\pythonProject\useful\ST-MapMatching\mapmatching\geo\ops\point2line.py", line 132, in project_points_2_linestrings
    proj_df.loc[:, att_lst] = proj_df.apply(
  File "D:\Anaconda3\envs\stmm\lib\site-packages\pandas\core\frame.py", line 9568, in apply
    return op.apply().__finalize__(self, method="apply")
  File "D:\Anaconda3\envs\stmm\lib\site-packages\pandas\core\apply.py", line 764, in apply
    return self.apply_standard()
  File "D:\Anaconda3\envs\stmm\lib\site-packages\pandas\core\apply.py", line 891, in apply_standard
    results, res_index = self.apply_series_generator()
  File "D:\Anaconda3\envs\stmm\lib\site-packages\pandas\core\apply.py", line 907, in apply_series_generator
    results[i] = self.f(v)
  File "D:\pythonProject\useful\ST-MapMatching\mapmatching\geo\ops\point2line.py", line 133, in <lambda>
    lambda x: project_point_2_linestring(
  File "D:\pythonProject\useful\ST-MapMatching\mapmatching\geo\ops\point2line.py", line 32, in project_point_2_linestring
    dist = line.project(point, normalized)
  File "D:\Anaconda3\envs\stmm\lib\site-packages\shapely\geometry\base.py", line 827, in project
    return shapely.line_locate_point(self, other, normalized=normalized)
  File "D:\Anaconda3\envs\stmm\lib\site-packages\shapely\decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\stmm\lib\site-packages\shapely\linear.py", line 88, in line_locate_point
    return lib.line_locate_point_normalized(line, other)
shapely.errors.GEOSException: IllegalArgumentException: LinearIterator only supports lineal geometry components

Process finished with exit code 1

**Comment by wenke727** [comment]
代码是在Linux下开发的，尚未在Windows上做适配。

该 Bug 是在window系统下，图的节点编号数值在数值转换时溢出
需要修改/mapmatching/match/candidatesGraph.py#L96：

```python
# gt.loc[:, ['src', 'dst']] = gt.loc[:, ['src', 'dst']].astype(int)
gt.loc[:, ['src', 'dst']] = gt.loc[:, ['src', 'dst']].astype(np.int64)
```

但没有进行全部代码的review和修改，可能还会有类似的问题。没有进行全部代码的review和修改，可能还会有类似的问题。

**Comment by yanglin-code** [comment]
谢谢大佬
