### ISSUE TITLE
下载解析路网数据失败

### ISSUE THREAD

**Issue by yanglin-code** [wenke727/ST-MapMatching#11]
换到Linux中运行了。给的样例数据路网数据覆盖不了第15条轨迹。然后试着调整了下载路网的经纬度，报了这样的错。
    
Parse ways: 0.19 s
2023-04-13 20:15:09.985 | DEBUG    | mapmatching.osmnet.parse_osm_xml:_parse_xml:231 - 	Drop duplicates ways, way ids: []
Parse nodes: 0.30 s
Transform to Dataframe: 0.59 s, node len: 7008
Combine edges: 100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 770/770 [00:01<00:00, 662.97it/s]
	Simplify the graph, len 7495 -> 2153, 71.27 % off
	Add revert edge, len 2153 -> 2264, 5.16 % up
2023-04-13 20:15:12.271 | DEBUG    | mapmatching.osmnet.parse_osm_xml:check_multi_edges:165 - Exists 32 multi-egdes: 
	{772, 517, 773, 779, 1937, 1556, 1177, 1309, 1182, 1311, 289, 1569, 298, 556, 1589, 312, 826, 827, 1345, 837, 719, 1872, 853, 855, 1112, 1139, 1653, 885, 1143, 2040, 1787, 894}
Traceback (most recent call last):
  File "/tmp/pycharm_project_650/demo.py", line 7, in <module>
    net = build_geograph(bbox=[113.920228, 22.526326, 113.937015, 22.5755998],
  File "/tmp/pycharm_project_650/mapmatching/osmnet/build_graph.py", line 28, in build_geograph
    df_nodes, df_edges, df_ways = parse_xml_to_graph(xml_fn, *args, **kwargs)
  File "/tmp/pycharm_project_650/mapmatching/osmnet/parse_osm_xml.py", line 362, in parse_xml_to_graph
    df_edges = _process_multi_edges(df_edges, ori_df_edges, df_ways)
  File "/tmp/pycharm_project_650/mapmatching/osmnet/parse_osm_xml.py", line 332, in _process_multi_edges
    neg_df_edges = swap_od(ori_df_edges.loc[neg_od_set])
  File "/tmp/pycharm_project_650/mapmatching/osmnet/twoway_edge.py", line 9, in swap_od
    df_edge_rev.loc[:, 'dir']       = -1
  File "/root/anaconda3/envs/stmm/lib/python3.9/site-packages/pandas/core/indexing.py", line 818, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/root/anaconda3/envs/stmm/lib/python3.9/site-packages/pandas/core/indexing.py", line 1718, in _setitem_with_indexer
    raise ValueError(
ValueError: cannot set a frame with no defined index and a scalar

**Comment by wenke727** [comment]
bbox 范围，我复现下，大概率是反向的道路的dataframe 为空

**Comment by wenke727** [comment]
新版本（V2.0.5）已增加对空 Dataframe 边界条件的处理
