### ISSUE TITLE
KeyError: 'MISSING'

### ISSUE THREAD

**Issue by Lezsin** [wenke727/ST-MapMatching#5]
作者您好！我的毕业设计涉及到您所做的项目，于是下载了您的“v1.1.1”版源码进行学习。在初步配置之后运行 main.py，我遇到了这样的报错：

```
D:\Graduation` project\venv\lib\site-packages\geopandas\_compat.py:84: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(
Traceback (most recent call last):
  File "D:/Graduation Project/wenke727_ST-Matching/src/main.py", line 1, in <module>
    from DigraphOSM import DigraphOSM
  File "D:\Graduation Project\wenke727_ST-Matching\src\DigraphOSM.py", line 7, in <module>
    import geopandas as gpd
  File "D:\Graduation project\venv\lib\site-packages\geopandas\__init__.py", line 3, in <module>
    from geopandas.geoseries import GeoSeries  # noqa
  File "D:\Graduation project\venv\lib\site-packages\geopandas\geoseries.py", line 12, in <module>
    from geopandas.base import GeoPandasBase, _delegate_property
  File "D:\Graduation project\venv\lib\site-packages\geopandas\base.py", line 13, in <module>
    from .array import GeometryArray, GeometryDtype
  File "D:\Graduation project\venv\lib\site-packages\geopandas\array.py", line 25, in <module>
    from . import _vectorized as vectorized
  File "D:\Graduation project\venv\lib\site-packages\geopandas\_vectorized.py", line 39, in <module>
    type_mapping = {p.value: _names[p.name] for p in pygeos.GeometryType}
  File "D:\Graduation project\venv\lib\site-packages\geopandas\_vectorized.py", line 39, in <dictcomp>
    type_mapping = {p.value: _names[p.name] for p in pygeos.GeometryType}
KeyError: 'MISSING'
```
环境：Windows 11 家庭版，Pycharm Pro 2021.2，Python 3.8.6
不知道您是否愿意帮我看看，万分感谢！

**Comment by wenke727** [comment]
看提示，应该是 geopandas 安装的问题，可以试下用 conda 安装。
conda install -c conda-forge geopandas

**Comment by Lezsin** [comment]
> 看提示，应该是 geopandas 安装的问题，可以试下用 conda 安装。 conda install -c conda-forge geopandas

非常感谢您的回复！我尝试用miniconda配置了一个新的虚拟环境，并且用conda安装了geopandas=0.8.1，仍然出现了同样的报错，决定还是再另想办法，不耽误您的时间了！再次感谢！
