### ISSUE TITLE
shapely.errors.GEOSException

### ISSUE THREAD

**Issue by Lezsin** [wenke727/ST-MapMatching#8]
在运行 demo.py 的过程中，我遇到了新的问题：
```
Traceback (most recent call last):
  File "D:\Graduation Projects\wenke727_ST-Matching_204\demo.py", line 28, in <module>
    proj_traj = matcher.project(traj, path)
  File "D:\Graduation Projects\wenke727_ST-Matching_204\mapmatching\matching.py", line 211, in project
    ps = project_points_2_linestrings(
  File "D:\Graduation Projects\wenke727_ST-Matching_204\mapmatching\geo\ops\point2line.py", line 132, in project_points_2_linestrings
    proj_df.loc[:, att_lst] = proj_df.apply(
  File "D:\Miniconda3\envs\ST-Matching\lib\site-packages\pandas\core\frame.py", line 9568, in apply
    return op.apply().__finalize__(self, method="apply")
  File "D:\Miniconda3\envs\ST-Matching\lib\site-packages\pandas\core\apply.py", line 764, in apply
    return self.apply_standard()
  File "D:\Miniconda3\envs\ST-Matching\lib\site-packages\pandas\core\apply.py", line 891, in apply_standard
    results, res_index = self.apply_series_generator()
  File "D:\Miniconda3\envs\ST-Matching\lib\site-packages\pandas\core\apply.py", line 907, in apply_series_generator
    results[i] = self.f(v)
  File "D:\Graduation Projects\wenke727_ST-Matching_204\mapmatching\geo\ops\point2line.py", line 133, in <lambda>
    lambda x: project_point_2_linestring(
  File "D:\Graduation Projects\wenke727_ST-Matching_204\mapmatching\geo\ops\point2line.py", line 32, in project_point_2_linestring
    dist = line.project(point, normalized)
  File "D:\Miniconda3\envs\ST-Matching\lib\site-packages\shapely\geometry\base.py", line 827, in project
    return shapely.line_locate_point(self, other, normalized=normalized)
  File "D:\Miniconda3\envs\ST-Matching\lib\site-packages\shapely\decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "D:\Miniconda3\envs\ST-Matching\lib\site-packages\shapely\linear.py", line 88, in line_locate_point
    return lib.line_locate_point_normalized(line, other)
shapely.errors.GEOSException: IllegalArgumentException: LinearIterator only supports lineal geometry components

进程已结束，退出代码为 1
```
不知道您对此有什么好的建议呢？

**Comment by wenke727** [comment]
抱歉，代码目前仅在 Linux 系统上测试。报错的类型是 `proj_df` 中间变量的 geometry 并非全部是 LineString。可能是 Windows 系统不兼容，争取下周适配

**Comment by Lezsin** [comment]
感谢您的回复！
我决定部署一个 Linux 环境来学习您的代码，不耽误您的时间了😊

**Comment by wenke727** [comment]
大致原因定位到了，在window系统下，图的节点编号数值在数值转换时溢出
需要修改[`/mapmatching/match/candidatesGraph.py#L96`](https://github.com/wenke727/ST-MapMatching/blob/main/mapmatching/match/candidatesGraph.py#L96)：
```python
# gt.loc[:, ['src', 'dst']] = gt.loc[:, ['src', 'dst']].astype(int)
gt.loc[:, ['src', 'dst']] = gt.loc[:, ['src', 'dst']].astype(np.int64)
```

但没有进行全部代码的review和修改，可能还会有类似的问题。
