### ISSUE TITLE
可视化失败

### ISSUE THREAD

**Issue by Lezsin** [wenke727/ST-MapMatching#9]
听取您上次的建议之后，我对`/mapmatching/match/candidatesGraph.py#L96`进行了修正，确实没有再报相同错误了。
但我又遇到了新的问题，在完成匹配过程并生成 log 文件后，并没有出现对应的结果图片。于是我在 ubuntu 18.04 LTS 下配置了一个新的环境，这次没有额外的报错，令人不解的是出现了和 windows 下一样的情况：没有出现任何结果图片。
本人水平实在有限，仿照教程在 demo.py 的第四步后添加了如下的语句：
```
import matplotlib.pyplot as plt
plt.show()
```
这次有图片出现，但其效果如下：
![visualize](https://user-images.githubusercontent.com/121026637/231039921-1d61d503-6172-427a-a8a1-d5e8f7da51f8.jpg)
您对此是否有什么思路？我该怎么样排除可能存在的错误呢？

**Comment by wenke727** [comment]
这是一个投影坐标转换的 bug，会在下一个版本中优化，直觉是多绘制了一个异常点(0, 0)，使得比例尺特别大，导致图形压缩严重。

比较快捷的方式是安装 [Tilemap](https://github.com/wenke727/TileMap)，安装如下：
```bash
cd Tilemap
sh install.sh
```
该库自动安装的脚步写的不好，安装结束后需试运行安装缺失的库，就可以绘制出和readme.md 一样效果的图。

**Comment by Lezsin** [comment]
感谢您的回复！我已经按要求安装了 Tilemap，接着遇到了一个奇怪的报错：
```
Traceback (most recent call last):
  File "/home/jwx/Code/Python/wenke727_ST-Matching_204/demo.py", line 22, in <module>
    res = matcher.matching(traj, top_k=5, dir_trans=True, details=False, plot=True,
  File "/home/jwx/Code/Python/wenke727_ST-Matching_204/mapmatching/utils/timer.py", line 36, in inner
    res = func(*args, **kwargs)
  File "/home/jwx/Code/Python/wenke727_ST-Matching_204/mapmatching/matching.py", line 126, in matching
    fig, ax = self.plot_result(_traj, res)
  File "/home/jwx/Code/Python/wenke727_ST-Matching_204/mapmatching/matching.py", line 266, in plot_result
    fig, ax = plot_matching_result(self.align_crs(traj.copy()), path, self.net)
  File "/home/jwx/Code/Python/wenke727_ST-Matching_204/mapmatching/match/visualization.py", line 206, in plot_matching_result
    fig, ax = plot_geodata(_df, figsize=(18, 12), tile_alpha=.7, reset_extent=False, alpha=0)
  File "/home/jwx/miniconda3/envs/ST-Matching/lib/python3.9/site-packages/tilemap/plotting.py", line 271, in plot_geodata
    add_basemap(ax, zoom, provider, interpolation, attribution, attribution_size, reset_extent, crs, resampling, cache_folder, **extra_imshow_args)
  File "/home/jwx/miniconda3/envs/ST-Matching/lib/python3.9/site-packages/tilemap/plotting.py", line 125, in add_basemap
    tile_processor = TileMap(**cfg)
  File "/home/jwx/miniconda3/envs/ST-Matching/lib/python3.9/site-packages/tilemap/tile.py", line 56, in __init__
    self.cache_folder.mkdir(exist_ok=True)
  File "/home/jwx/miniconda3/envs/ST-Matching/lib/python3.9/pathlib.py", line 1312, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pcl/minio/tile/Amap.Satellite'
```
这是否意味着我的安装还存在问题？我需要手动下载这份文件吗？

**Comment by wenke727** [comment]
目录的问题，可以通过显式设置 cache_folder 解决

```python
from tilemap.tile import set_tile_cache_floder
set_tile_cache_floder("your folder")
```

或者修改源码 `TileMap/tilemap/tile.py` 中的 L25

```python
CACHE_FOLDER = "your folder"
```

**Comment by Lezsin** [comment]
谢谢您！我已经设置为了自己的文件夹，并生成了对应的`Amap.Satellite`文件夹。
但自从安装好了 TIlemap 后，终端不再像之前一样打印出 log 记录（虽然 log 文件夹里的文件仍然在更新）。我好奇这是否是调用 Tilemap 使然？现在的终端没有打印任何东西，我并不确定这是否是符合预期的。
另外，假如我不自行加入`plt.show()`语句，仍然不会出现任何结果图片。即使我加入了这条语句，仍然会出现和之前一样的结果：
![visualize2](https://user-images.githubusercontent.com/121026637/231759233-d40d5349-38ac-43c0-8a31-d3d8c7a5fbd7.jpg)
（左侧有所生成的`Amap.Satellite`文件夹。新生成的图片和之前略有区别，但仍然有放缩的问题，且不包含任何瓦片）
我认为我在安装 Tilemap 的过程中可能还存在问题，您认为呢？

**Comment by wenke727** [comment]
该 bug 已在新版本（V2.0.5）中解决。

抱歉，是我在前面将 GeoGraph 的基础数据改为投影坐标后，现有的代码存在没有指定 crs 的 GeoDataFrame，两者绘制在一起就会出现上边的情况。

**Comment by Lezsin** [comment]
感谢您，我已经得到了正确的图像结果😊
